//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloSeguridad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int COD_USER { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> COD_ROL { get; set; }
        public Nullable<int> COD_ESTADO { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
